---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Preprocessing

```{r load_libraries_specific, include = FALSE}

library(ggnewscale)
library(khroma)
library(broom)
library(scico)
library(ggtext)

```

```{r check_if_model}

# model <- TRUE
model <- str_detect('{{product_name}}', "FESOM-REcoM|ETHZ_CESM")

```


## Load masks

```{r mask_and_map}

biome_mask <-
  read_rds(here::here("data/biome_mask.rds"))

region_mask <-
  read_rds(here::here("data/region_mask.rds"))

map <-
  read_rds(here::here("data/map.rds"))

key_biomes <-
  read_rds(here::here("data/key_biomes.rds"))

super_biomes <-
  read_rds(here::here("data/super_biomes.rds"))

super_biome_mask <-
  read_rds(here::here("data/super_biome_mask.rds"))

```


## Define labels and breaks


```{r define_labels_and_breaks_OIA_variables_change}

labels_breaks <- function(i_name) {
  
  if (i_name == "dco2") {
    i_legend_title <- "ΔpCO<sub>2</sub><br>(µatm)"
  }
  
  if (i_name == "dfco2") {
    i_legend_title <- "ΔfCO<sub>2</sub><br>(µatm)"
  }
  
  if (i_name == "atm_co2") {
    i_legend_title <- "pCO<sub>2,atm</sub><br>(µatm)"
  }
  
  if (i_name == "atm_fco2") {
    i_legend_title <- "fCO<sub>2,atm</sub><br>(µatm)"
  }
  
  if (i_name == "sol") {
    i_legend_title <- "K<sub>0</sub><br>(mol m<sup>-3</sup> µatm<sup>-1</sup>)"
  }
  
  if (i_name == "kw") {
    i_legend_title <- "k<sub>w</sub><br>(m yr<sup>-1</sup>)"
  }
  
  if (i_name == "kw_sol") {
    i_legend_title <- "k<sub>w</sub> K<sub>0</sub><br>(mol yr<sup>-1</sup> m<sup>-2</sup> µatm<sup>-1</sup>)"
  }
  
  if (i_name == "spco2") {
    i_legend_title <- "pCO<sub>2,ocean</sub><br>(µatm)"
  }
  
  if (i_name == "sfco2") {
    i_legend_title <- "fCO<sub>2,ocean</sub><br>(µatm)"
  }
  
  if (i_name == "intpp") {
    i_legend_title <- "NPP<sub>int</sub><br>(mol s<sup>-1</sup> m<sup>-2</sup>)"
  }

  if (i_name == "no3") {
    i_legend_title <- "NO<sub>3</sub><br>(μmol kg<sup>-1</sup>)"
  }

  if (i_name == "o2") {
    i_legend_title <- "O<sub>2</sub><br>(μmol kg<sup>-1</sup>)"
  }

  if (i_name == "dissic") {
    i_legend_title <- "DIC<br>(μmol kg<sup>-1</sup>)"
  }

  if (i_name == "sdissic") {
    i_legend_title <- "sDIC<br>(μmol kg<sup>-1</sup>)"
  }

  if (i_name == "cstar") {
    i_legend_title <- "C*<br>(μmol kg<sup>-1</sup>)"
  }

  if (i_name == "talk") {
    i_legend_title <- "TA<br>(μmol kg<sup>-1</sup>)"
  }

  if (i_name == "stalk") {
    i_legend_title <- "sTA<br>(μmol kg<sup>-1</sup>)"
  }
  
  if (i_name == "sfco2_total") {
    i_legend_title <- "total"
  }
  
  if (i_name == "sfco2_therm") {
    i_legend_title <- "thermal"
  }
  
  if (i_name == "sfco2_nontherm") {
    i_legend_title <- "non-thermal"
  }
  
  if (i_name == "fgco2") {
    i_legend_title <- "FCO<sub>2</sub><br>(mol m<sup>-2</sup> yr<sup>-1</sup>)"
  }
  
  if (i_name == "fgco2_hov") {
    i_legend_title <- "FCO<sub>2</sub><br>(PgC deg<sup>-1</sup> yr<sup>-1</sup>)"
  }
  
  if (i_name == "fgco2_int") {
    i_legend_title <- "FCO<sub>2</sub><br>(PgC yr<sup>-1</sup>)"
  }
  
  if (i_name == "thetao") {
    i_legend_title <- "Temp.<br>(°C)"
  }
  
  if (i_name == "temperature") {
    i_legend_title <- "SST<br>(°C)"
  }
  
  if (i_name == "salinity") {
    i_legend_title <- "SSS"
  }
  
  if (i_name == "so") {
    i_legend_title <- "salinity"
  }
  
  if (i_name == "chl") {
    i_legend_title <- "lg(Chl-a)<br>(lg(mg m<sup>-3</sup>))"
  }
  
  if (i_name == "mld") {
    i_legend_title <- "MLD<br>(m)"
  }
  
  if (i_name == "press") {
    i_legend_title <- "pressure<sub>atm</sub><br>(Pa)"
  }
  
  if (i_name == "wind") {
    i_legend_title <- "Wind <br>(m sec<sup>-1</sup>)"
  }
  
  if (i_name == "SSH") {
    i_legend_title <- "SSH <br>(m)"
  }
  
  if (i_name == "fice") {
    i_legend_title <- "Sea ice <br>(%)"
  }
  
    
  if (i_name == "resid_fgco2") {
    i_legend_title <-
      "Observed"
  }
    
  if (i_name == "resid_fgco2_dfco2") {
    i_legend_title <-
      "ΔfCO<sub>2</sub>"
  }
    
  if (i_name == "resid_fgco2_kw_sol") {
    i_legend_title <-
      "k<sub>w</sub> K<sub>0</sub>"
  }
    
  if (i_name == "resid_fgco2_dfco2_kw_sol") {
    i_legend_title <-
      "k<sub>w</sub> K<sub>0</sub> X ΔfCO<sub>2</sub>"
  }
    
  if (i_name == "resid_fgco2_sum") {
    i_legend_title <-
      "∑"
  }
    
  if (i_name == "resid_fgco2_offset") {
    i_legend_title <-
      "Obs. - ∑"
  }
  
  all_labels_breaks <- lst(i_legend_title)
  
  return(all_labels_breaks)
  
}

x_axis_labels <-
  c(
    "dco2" = labels_breaks("dco2")$i_legend_title,
    "dfco2" = labels_breaks("dfco2")$i_legend_title,
    "atm_co2" = labels_breaks("atm_co2")$i_legend_title,
    "atm_fco2" = labels_breaks("atm_fco2")$i_legend_title,
    "sol" = labels_breaks("sol")$i_legend_title,
    "kw" = labels_breaks("kw")$i_legend_title,
    "kw_sol" = labels_breaks("kw_sol")$i_legend_title,
    "intpp" = labels_breaks("intpp")$i_legend_title,
    "no3" = labels_breaks("no3")$i_legend_title,
    "o2" = labels_breaks("o2")$i_legend_title,
    "dissic" = labels_breaks("dissic")$i_legend_title,
    "sdissic" = labels_breaks("sdissic")$i_legend_title,
    "cstar" = labels_breaks("cstar")$i_legend_title,
    "talk" = labels_breaks("talk")$i_legend_title,
    "stalk" = labels_breaks("stalk")$i_legend_title,
    "spco2" = labels_breaks("spco2")$i_legend_title,
    "sfco2" = labels_breaks("sfco2")$i_legend_title,
    "sfco2_total" = labels_breaks("sfco2_total")$i_legend_title,
    "sfco2_therm" = labels_breaks("sfco2_therm")$i_legend_title,
    "sfco2_nontherm" = labels_breaks("sfco2_nontherm")$i_legend_title,
    "fgco2" = labels_breaks("fgco2")$i_legend_title,
    "fgco2_hov" = labels_breaks("fgco2_hov")$i_legend_title,
    "fgco2_int" = labels_breaks("fgco2_int")$i_legend_title,
    "thetao" = labels_breaks("thetao")$i_legend_title,
    "temperature" = labels_breaks("temperature")$i_legend_title,
    "salinity" = labels_breaks("salinity")$i_legend_title,
    "so" = labels_breaks("so")$i_legend_title,
    "chl" = labels_breaks("chl")$i_legend_title,
    "mld" = labels_breaks("mld")$i_legend_title,
    "press" = labels_breaks("press")$i_legend_title,
    "wind" = labels_breaks("wind")$i_legend_title,
    "SSH" = labels_breaks("SSH")$i_legend_title,
    "fice" = labels_breaks("fice")$i_legend_title,
    "resid_fgco2" = labels_breaks("resid_fgco2")$i_legend_title,
    "resid_fgco2_dfco2" = labels_breaks("resid_fgco2_dfco2")$i_legend_title,
    "resid_fgco2_kw_sol" = labels_breaks("resid_fgco2_kw_sol")$i_legend_title,
    "resid_fgco2_dfco2_kw_sol" = labels_breaks("resid_fgco2_dfco2_kw_sol")$i_legend_title,
    "resid_fgco2_sum" = labels_breaks("resid_fgco2_sum")$i_legend_title,
    "resid_fgco2_offset" = labels_breaks("resid_fgco2_offset")$i_legend_title
  )


```

## Analysis settings

```{r analysis_settings}

name_quadratic_fit <- c("atm_co2", "atm_fco2", "spco2", "sfco2")

start_year <- 1990

name_divergent <- c("dco2", "dfco2", "fgco2", "fgco2_hov", "fgco2_int")

```


## Data preprocessing

```{r temporal_boundaries}

pco2_product <-
  pco2_product %>%
  filter(year >= start_year)

```

```{r temporal_boundaries_interior, eval=model}

pco2_product_interior <-
  pco2_product_interior %>%
  filter(time >= ymd(paste0(start_year, "-01-01")))

```


```{r biome_mask}

biome_mask <- biome_mask %>% 
  mutate(area = earth_surf(lat, lon))

pco2_product <-
  full_join(pco2_product,
            biome_mask)

# set all values outside biome mask to NA

pco2_product <-
  pco2_product %>%
  mutate(across(-c(lat, lon, time, area, year, month, biome), 
                ~ if_else(is.na(biome), NA, .)))

```

## Compuations

```{r compute_coarse_resolution_maps}

# apply coarse grid

pco2_product_coarse <-
  pco2_product %>%
  mutate(lon_grid = lon,
         lat_grid = lat)

# pco2_product_coarse <-
#   m_grid_horizontal_coarse(pco2_product)

# pco2_product_coarse <-
#   pco2_product_coarse %>%
#   select(-c(lon, lat, time, biome)) %>%
#   group_by(year, month, lon_grid, lat_grid) %>%
#   summarise(across(-area,
#                    ~ weighted.mean(., area))) %>%
#   ungroup() %>%
#   rename(lon = lon_grid, lat = lat_grid)

pco2_product_coarse <-
  pco2_product_coarse %>%
  select(-c(lon, lat, time, biome)) %>%
  fgroup_by(year, month, lon_grid, lat_grid) %>%
  fmean(w = area,
        keep.w = FALSE,
        na.rm = FALSE) %>%
  rename(lon = lon_grid, lat = lat_grid)

pco2_product_coarse <-
  pco2_product_coarse %>%
  pivot_longer(-c(year, month, lon, lat)) %>% 
  drop_na() %>%
  pivot_wider()

gc()

# compute annual means

pco2_product_coarse_annual <-
  pco2_product_coarse %>%
  select(-month) %>% 
  fgroup_by(year, lon, lat) %>%
  fmean(na.rm = FALSE)

pco2_product_coarse_annual <-
  pco2_product_coarse_annual %>% 
  pivot_longer(-c(year, lon, lat))

## compute monthly means

pco2_product_coarse_monthly <-
  pco2_product_coarse %>%
  fgroup_by(year, month, lon, lat) %>%
  fmean()

pco2_product_coarse_monthly <-
  pco2_product_coarse_monthly %>% 
  pivot_longer(-c(year, month, lon, lat))

gc()

```

```{r compute_global_means_and_integrals}

pco2_product_monthly_global <-
  pco2_product %>%
  filter(!is.na(fgco2)) %>%
  mutate(fgco2_int = fgco2) %>%
  mutate(biome = case_when(str_detect(biome, "SO-") ~ "Southern Ocean",
                           TRUE ~ "other")) %>%
  filter(biome == "other") %>%
  select(-c(lon, lat, year, month, biome)) %>%
  group_by(time) %>%
  summarise(across(-c(fgco2_int, area),
                   ~ weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_int,
                   ~ sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>%
  ungroup()

pco2_product_monthly_biome <-
  pco2_product %>%
  filter(!is.na(fgco2)) %>% 
  mutate(fgco2_int = fgco2) %>% 
  select(-c(lon, lat, year, month)) %>% 
  group_by(time, biome) %>%
  summarise(across(-c(fgco2_int, area),
                   ~ weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_int,
                   ~ sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>%
  ungroup()


pco2_product_monthly_biome_super <-
  pco2_product %>%
  filter(!is.na(fgco2)) %>% 
  mutate(fgco2_int = fgco2) %>% 
  mutate(
    biome = case_when(
      str_detect(biome, "NA-") ~ "North Atlantic",
      str_detect(biome, "NP-") ~ "North Pacific",
      str_detect(biome, "SO-") ~ "Southern Ocean",
      TRUE ~ "other"
    )
  ) %>%
  filter(biome != "other") %>%
  select(-c(lon, lat, year, month)) %>%
  group_by(time, biome) %>%
  summarise(across(-c(fgco2_int, area),
                   ~ weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_int,
                   ~ sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>%
  ungroup()

pco2_product_monthly <-
  bind_rows(pco2_product_monthly_global %>%
              mutate(biome = "Global"),
            pco2_product_monthly_biome,
            pco2_product_monthly_biome_super)

rm(
  pco2_product_monthly_global,
  pco2_product_monthly_biome,
  pco2_product_monthly_biome_super
)


pco2_product_monthly <-
  pco2_product_monthly %>% 
  filter(!is.na(biome))

pco2_product_monthly <-
  pco2_product_monthly %>%
  mutate(year = year(time),
         month = month(time),
         .after = time)

pco2_product_monthly <-
  pco2_product_monthly %>%
  pivot_longer(-c(time, year, month, biome))


```

```{r generate_biome_mean_profiles, eval=model}

pco2_product_interior <- 
  left_join(
    biome_mask,
    pco2_product_interior
  )

pco2_product_profiles <- pco2_product_interior %>%
  fselect(-c(lat, lon)) %>%
  fgroup_by(biome, depth, time) %>% {
    add_vars(fgroup_vars(., "unique"),
             fmean(.,
                   w = area,
                   keep.w = FALSE,
                   keep.group_vars = FALSE))
  }

pco2_product_profiles <-
  pco2_product_profiles %>%
  mutate(
    year = year(time),
    month = month(time)
  )

gc()

```


```{r generate_zonal_mean_sections, eval=model}

pco2_product_interior <- 
  left_join(
    region_mask,
    pco2_product_interior %>% select(-c(biome, area))
  )

pco2_product_zonal_mean <- pco2_product_interior %>%
  fselect(-c(lon)) %>%
  fgroup_by(region, depth, lat, time) %>% {
    add_vars(fgroup_vars(., "unique"),
             fmean(.,
                   keep.group_vars = FALSE))
  }

pco2_product_zonal_mean <-
  pco2_product_zonal_mean %>%
  mutate(
    year = year(time),
    month = month(time)
  )

gc()

# pco2_product_zonal_mean %>% 
#   filter(region == "atlantic",
#          year == 2023,
#          month == 1) %>% 
#   ggplot(aes(lat, depth, z = no3)) +
#   geom_contour_filled() +
#   scale_y_reverse() +
#   scale_fill_viridis_d()

rm(pco2_product_interior)
gc()

```




# Absolute values

## Hovmoeller plots

The following Hovmoeller plots show the value of each variable as provided through the pCO2 product. Hovmoeller plots are first presented as annual means, and than as monthly means.

### Annual means

```{r hovmoeller_annual_absolute, fig.asp=0.5}

pco2_product_hovmoeller_monthly_annual <-
  pco2_product %>%
  mutate(fgco2_int = fgco2) %>% 
  select(-c(lon, time, month, biome)) %>%
  group_by(year, lat) %>%
  summarise(across(-c(fgco2_int, area),
                   ~ weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_int,
                   ~ sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>%
  ungroup() %>%
  rename(fgco2_hov = fgco2_int) %>% 
  filter(fgco2_hov != 0)

pco2_product_hovmoeller_monthly_annual <-
  pco2_product_hovmoeller_monthly_annual %>%
  pivot_longer(-c(year, lat)) %>% 
  drop_na()

pco2_product_hovmoeller_monthly_annual %>%
  filter(!(name %in% name_divergent)) %>% 
  group_split(name) %>%
  # tail(5) %>%
  map(
    ~ ggplot(data = .x,
             aes(year, lat, fill = value)) +
      geom_raster() +
      scale_fill_viridis_c(name = labels_breaks(.x %>% distinct(name))) +
      theme(legend.title = element_markdown()) +
      coord_cartesian(expand = 0) +
      labs(title = "Annual means",
           y = "Latitude") +
      theme(axis.title.x = element_blank())
  )

pco2_product_hovmoeller_monthly_annual %>%
  filter(name %in% name_divergent) %>% 
  group_split(name) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(year, lat, fill = value)) +
      geom_raster() +
      scale_fill_divergent(name = labels_breaks(.x %>% distinct(name))) +
      theme(legend.title = element_markdown()) +
      coord_cartesian(expand = 0) +
      labs(title = "Annual means",
           y = "Latitude") +
      theme(axis.title.x = element_blank())
  )


```


### Monthly means

```{r hovmoeller_monthly_absolute, fig.asp=0.5}

pco2_product_hovmoeller_monthly <-
  pco2_product %>%
  mutate(fgco2_int = fgco2) %>% 
  select(-c(lon, time, biome)) %>%
  group_by(year, month, lat) %>%
  summarise(across(-c(fgco2_int, area),
                   ~ weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_int,
                   ~ sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>%
  ungroup() %>%
  rename(fgco2_hov = fgco2_int) %>% 
  filter(fgco2_hov != 0)


pco2_product_hovmoeller_monthly <-
  pco2_product_hovmoeller_monthly %>%
  pivot_longer(-c(year, month, lat)) %>% 
  drop_na()

pco2_product_hovmoeller_monthly <-
  pco2_product_hovmoeller_monthly %>% 
  mutate(decimal = year + (month-1) / 12)

pco2_product_hovmoeller_monthly %>%
  filter(!(name %in% name_divergent)) %>%
  group_split(name) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(decimal, lat, fill = value)) +
      geom_raster() +
      scale_fill_viridis_c(name = labels_breaks(.x %>% distinct(name))) +
      theme(legend.title = element_markdown()) +
      labs(title = "Monthly means",
           y = "Latitude") +
      coord_cartesian(expand = 0) +
      theme(axis.title.x = element_blank())
  )

pco2_product_hovmoeller_monthly %>%
  filter(name %in% name_divergent) %>%
  group_split(name) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(decimal, lat, fill = value)) +
      geom_raster() +
      scale_fill_divergent(name = labels_breaks(.x %>% distinct(name))) +
      theme(legend.title = element_markdown()) +
      labs(title = "Monthly means",
           y = "Latitude") +
      coord_cartesian(expand = 0) +
      theme(axis.title.x = element_blank())
  )


```
