---
title: "Atmospheric CO2"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_specific, include = FALSE}

library(lubridate)
library(khroma)
library(broom)

```


# Read data

```{r read_data}

co2_mm_gl <- read_csv("../data/co2_mm_gl.csv", 
    skip = 38)

global_co2_merged <- read_table("../data/global_co2_merged.txt", 
    comment = "!",
    col_names = c("decimal", "average"))


atm_co2 <-
  bind_rows(
    co2_mm_gl %>%
      select(decimal, average) %>%
      mutate(source = "NOAA - Global marine surface"),
    global_co2_merged %>%
      mutate(source = "GCB - MLO & SPO")
  )

atm_co2 <- 
atm_co2 %>% 
  mutate(date = date_decimal(decimal),
         year = year(date),
         month = month(date))


```


```{r xco2_mbl_NOAA, eval=FALSE}

co2_surface <- read_table(here::here("data/input/atm_co2/co2_GHGreference.767706493_surface.txt"), 
    col_names = FALSE, skip = 76)

co2_surface <-
  co2_surface[c(1, seq(2, 83, 2))]

names(co2_surface) <- c("time",
                        as.character(seq(-1, 1, 0.05)))

# conversion to degrees latitude
# 180/pi * asin(-1)

co2_surface <-
  co2_surface %>%
  pivot_longer(-time,
               names_to = "lat",
               values_to = "xco2")

co2_surface <-
  co2_surface %>%
  mutate(lat = as.numeric(lat))

co2_surface %>% 
  filter(time > 2010) %>% 
  ggplot(aes(time, lat, fill = xco2)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma") +
  # scale_y_continuous(sec.axis = sec_axis(~ sin(.))) +
  coord_cartesian(expand = 0)



surface_mbl <- read_table("data/input/atm_co2/surface.mbl.co2", 
    col_names = FALSE)

names(surface_mbl) <- c("time",
                        as.character(seq(-1, 1, 0.05)))

# conversion to degrees latitude
# 180/pi * asin

surface_mbl <-
  surface_mbl %>%
  pivot_longer(-time,
               names_to = "lat",
               values_to = "xco2")

surface_mbl <-
  surface_mbl %>%
  mutate(lat = as.numeric(lat))

surface_mbl %>% 
  filter(time > 2010) %>% 
  ggplot(aes(time, lat, fill = xco2)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma") +
  coord_cartesian(expand = 0)

co2_merge <- 
bind_rows(co2_surface %>% mutate(product = "website"),
          surface_mbl %>% mutate(product = "preliminary"))

co2_merge %>%
  filter(time > 2010) %>%
  ggplot(aes(time, lat, fill = xco2)) +
  geom_tile() +
  scale_fill_viridis_c(option = "magma") +
  coord_cartesian(expand = 0) +
  facet_wrap(~ product, ncol = 1)

library(colorspace)

co2_merge_delta <-
co2_merge %>%
  pivot_wider(names_from = product,
              values_from = xco2) %>% 
  mutate(delta_xco2 = preliminary - website) %>% 
  filter(!is.na(delta_xco2))

co2_merge_delta %>% 
  filter(time > 2010) %>%
  ggplot(aes(time, lat, fill = delta_xco2)) +
  geom_tile() +
  scale_fill_divergent() +
  scale_x_continuous(breaks = seq(1900,2100,5)) +
  coord_cartesian(expand = 0)

library(khroma)
co2_merge_delta %>%
  mutate(lat = cut(lat,sin(c(-90,seq(-75,75,30),90)/180*pi))) %>% 
  group_by(lat, time) %>%
  summarise(delta_xco2 = mean(delta_xco2, na.rm = TRUE)) %>% 
  ungroup() %>% 
  # filter(time > 2010) %>%
  ggplot(aes(time, delta_xco2, col = lat)) +
  geom_path() +
  scale_color_bright() +
  coord_cartesian(expand = 0)


```



```{r plot_time_series}

atm_co2 %>% 
  filter(decimal > 2010) %>% 
  ggplot(aes(decimal, average, col = source)) +
  geom_path() +
  geom_point() +
  labs(y = expression(Atm.~CO[2]~(ppm))) +
  geom_smooth(method = "lm", se = FALSE) +
  scale_color_okabeito() +
  theme_bw() +
  scale_x_continuous(breaks = seq(1900,2100,2)) +
  theme(axis.title.x = element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.8,0.2))
  
  

```

```{r monthly_anomalies}


atm_co2 <-
  atm_co2 %>%
  filter(year < 2023 | source != "GCB - MLO & SPO")

atm_co2 <-
  atm_co2 %>%
  group_by(year, source) %>%
  mutate(annual_mean = mean(average)) %>%
  ungroup() %>%
  mutate(monthly_anomaly = average - annual_mean)

atm_co2 %>% 
  filter(decimal > 2013,
         decimal < 2023) %>%
  ggplot(aes(month, monthly_anomaly, col = source, group = interaction(source, year))) +
  geom_path() +
  geom_point() +
  labs(y = expression(Monthly~anomaly~from~annual~mean~(ppm)),
       title = expression(Atmospheric~CO[2]~seasonality),
       subtitle = "2013 - 2022") +
  scale_color_manual(values = c("#000000", "#E69F00", "#56B4E9")) +
  theme_bw() +
  scale_x_continuous(breaks = seq(1,12,1), expand = c(0.01,0)) +
  theme(legend.title = element_blank(),
        legend.position = c(0.3,0.2))

ggsave(
  here::here(
    paste0(
      "output/atm_CO2_seasonality.png"
    )
  ),
  width = 6,
  height = 4,
  dpi = 600,
  bg = "white"
)


atm_co2 %>% 
  filter(decimal > 1980,
         decimal < 2023) %>% 
  ggplot(aes(month, monthly_anomaly, group = interaction(year), col = year)) +
  geom_path() +
  geom_point() +
  labs(y = expression(Monthly~anomaly~atm.~CO[2]~(ppm))) +
  scale_color_viridis_c() +
  theme_bw() +
  scale_x_continuous(breaks = seq(1,12,3)) +
  facet_wrap(~ source) +
  theme(legend.title = element_blank())

atm_co2_monthly_anomaly <-
  atm_co2 %>%
  filter(decimal > 2013,
         decimal < 2023) %>%
  group_by(source, month) %>%
  summarise(monthly_anomaly = mean(monthly_anomaly),
            decimal_mean = mean(decimal - year)) %>%
  ungroup()


atm_co2_annual_means <-
  atm_co2 %>%
  group_by(source, year) %>%
  summarise(annual_mean = mean(average)) %>%
  ungroup()

atm_co2_annual_means %>% 
  filter(year >= 2013,
         year <= 2022) %>% 
  group_by(source) %>%
  summarise(long_term_mean = mean(annual_mean)) %>%
  ungroup() %>% 
  pull(long_term_mean)


annual_mean_2023_predicted <-
  atm_co2 %>%
  filter(decimal > 2013,
         decimal < 2023) %>%
  group_by(source, year) %>%
  summarise(annual_mean = mean(average)) %>%
  ungroup() %>%
  nest(data = -source) %>%
  mutate(fit = map(data, ~ lm(annual_mean ~ year, data = .x)),
         tidied = map(fit, tidy)) %>%
  unnest(tidied) %>%
  select(source, term, estimate) %>%
  pivot_wider(names_from = term,
              values_from = estimate) %>%
  mutate(annual_mean = `(Intercept)` + year * 2023) %>%
  filter(source == "GCB - MLO & SPO") %>%
  pull(annual_mean)

  
atm_co2_monthly_anomaly <-
  atm_co2_monthly_anomaly %>%
  filter(source == "GCB - MLO & SPO") %>%
  mutate(
    year = 2023,
    decimal = year + decimal_mean,
    annual_mean = annual_mean_2023_predicted,
    average =  annual_mean + monthly_anomaly,
    source = "GCB - MLO & SPO (linear prediction)",
    date = date_decimal(decimal)
  ) %>%
  select(-decimal_mean)


atm_co2_predicted <-
  bind_rows(atm_co2 %>% filter(year < 2023 |
                                 source != "GCB - MLO & SPO"),
            atm_co2_monthly_anomaly)

atm_co2_annual_means %>% 
  filter(year > 2021)

atm_co2_predicted %>% 
  filter(decimal > 2013) %>% 
  ggplot() +
  geom_path(aes(decimal, average, col = source)) +
  geom_point(aes(decimal, average, col = source)) +
  geom_path(aes(decimal, annual_mean, col = source, group = interaction(source, year),
                linetype = "annual mean")) +
  scale_linetype_manual(values = 2) +
  labs(y = expression(CO[2]~(ppm)),
       title = expression(Atmospheric~CO[2]~timeseries),
       subtitle = "2013 - 2022") +
  scale_color_manual(values = c("#000000", "#56B4E9", "#E69F00")) +
  theme_bw() +
  scale_x_continuous(breaks = seq(1900,2100,2), expand = c(0.01,0)) +
  theme(axis.title.x = element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.3,0.7))


ggsave(
  here::here(
    paste0(
      "output/atm_CO2_timeseries.png"
    )
  ),
  width = 6,
  height = 4,
  dpi = 600,
  bg = "white"
)


```

