---
title: "CMEMS"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_read_data, include = FALSE}

library(stars)
library(lubridate)

```

# Read data

```{r define_paths}

path_pCO2_products <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/"

path_CMEMS <- paste0(path_pCO2_products, "cmems_ffnn/v2023/r100_regridded/")

```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)
nc <-
  nc_open(paste0(
    path_pCO2_products,
    "VLIZ-SOM_FFN/VLIZ-SOM_FFN_vBAMS2024.nc"
  ))

nc <-
  nc_open(paste0(
    path_CMEMS,
    "kw_OceanSODA_ETHZ_HR_LR-v2023.01-1982_2023.nc"
  ))

nc <-
  nc_open(paste0(
    path_CMEMS,
    "CO2_fluxes/fluxCO2_model_v2022_r100_202402.nc"
  ))

nc <-
  nc_open(paste0(
    path_CMEMS,
    "SSH_r100_199205.nc"
  ))

nc <-
  nc_open("/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/cmems_ffnn/v2020/v2020.nc")

print(nc)

ncatt_get(nc, varid = "time")
ncvar_get(nc, varid = "time")

```


```{r read_CMEMS}

CMEMS_files <- list.files(path = path_CMEMS)
CMEMS_files <- CMEMS_files[!(CMEMS_files %>% str_detect("fuCO2_clim"))]


# CMEMS_files <- str_remove(CMEMS_files, ".nc")
# CMEMS_files_dates <- str_sub(CMEMS_files, start = -6)
# CMEMS_files_names <- str_sub(CMEMS_files, end = -8)
# CMEMS_files_names <- str_remove(CMEMS_files_names, "_r100")
# CMEMS_files <- bind_cols(file_name_variable = CMEMS_files_names, file_name_date = CMEMS_files_dates)
# library(lubridate)
# CMEMS_files <- CMEMS_files %>%
#   mutate(date = ym(file_name_date))
# CMEMS_files %>% 
#   filter(year(date) >= 2023) %>% 
#   ggplot(aes(file_name_date, file_name_variable)) +
#   geom_point()



CMEMS_files <- CMEMS_files[!(CMEMS_files %>% str_detect("UV"))]
CMEMS_files <- CMEMS_files[!(CMEMS_files %>% str_detect("Ps"))]
CMEMS_files <- CMEMS_files[!(CMEMS_files %>% str_detect("Sea_Ice"))]
print(CMEMS_files, max = 5000)

file_names <- str_split(CMEMS_files, "_", simplify = TRUE)[,1] %>% unique()


for (i_file_name in file_names) {
  # i_file_name <- file_names[1]
  CMEMS_files_var <-
    CMEMS_files[CMEMS_files %>% str_detect(i_file_name)]
  
  if(i_file_name == "xCO2"){
  CMEMS_files_var <-
    CMEMS_files_var[!CMEMS_files_var %>% str_detect("fluxCO2")]
  }
  
  for (i_name in CMEMS_files_var) {
    # i_name <- CMEMS_files_var[466]
    # print(i_name)
    
    library(ncdf4)
    nc <- nc_open(paste0(path_CMEMS, i_name))
    var_name <- names(nc$var)[1]
    
    i_pco2_product_var <-
      read_ncdf(paste0(path_CMEMS, i_name),
                make_units = FALSE,
                var = var_name)
    
    if (exists("pco2_product_var")) {
      pco2_product_var <-
        c(pco2_product_var,
          i_pco2_product_var)
    }
    
    if (!exists("pco2_product_var")) {
      pco2_product_var <- i_pco2_product_var
    }
    
    # ggplot() +
    #   geom_stars(data = pco2_product_var) +
    #   scale_fill_viridis_c(trans = "log10", na.value = "red") +
    #   facet_wrap(~ time)
    
    
  }
  
  pco2_product_var <- pco2_product_var %>%
  as_tibble()
  
  # ggplot() +
  #   geom_raster(data = pco2_product_var, aes(lon, lat, fill = CHL)) +
  #   scale_fill_viridis_c(trans = "log10", na.value = "red") +
  #   facet_wrap( ~ time)
  
  if (exists("pco2_product")) {
    pco2_product <-
      full_join(pco2_product,
                pco2_product_var)
  }
  
  if (!exists("pco2_product")) {
    pco2_product <- pco2_product_var
  }
  
  rm(pco2_product_var)
  
}

rm(i_pco2_product_var,
   nc, var_name,
   i_file_name, file_names,
   i_name, CMEMS_files_var,
   CMEMS_files)
# rm(pco2_product)

pco2_product <-
  pco2_product %>%
  rename(chl = CHL,
         mld = MLD,
         atm_co2 = CO2,
         fgco2 = fCO2_mean,
         salinity = SSS,
         temperature = SST)

pco2_product <-
  pco2_product %>%
  mutate(
    area = earth_surf(lat, lon),
    year = year(time),
    month = month(time),
    time = ymd(paste(year, month, "15", sep = "-"))
  )

pco2_product <-
  pco2_product %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon),
         fgco2 = -fgco2,
         chl = log10(chl),
         mld = log10(mld))

# ggplot() +
#   geom_raster(data = pco2_product %>%
#                 filter(year == 2023,
#                        month %in% c(9,10),
#                        !is.na(chl)),
#               aes(lon, lat, fill = chl)) +
#   scale_fill_viridis_c(na.value = "red") +
#   facet_wrap(~ month)

pco2_product <-
  pco2_product %>% 
  filter(year <= 2023)

```


```{r read_CMEMS_old, eval=FALSE}

names <- c("CO2_fluxes", "CO2_fugacity")

for (i_name in names) {
  
  # i_name <- names[2]
  
  CMEMS_files <- list.files(path = paste0(path_CMEMS, i_name, "/"),
                            full.names = TRUE)
  
  # i_CMEMS_files <- CMEMS_files[2]
  
  i_pco2_product <-
    read_stars(CMEMS_files,
               make_units = FALSE,
               ignore_bounds = TRUE,
               quiet = TRUE)
  
  if (exists("pco2_product")) {
    pco2_product <-
      c(pco2_product,
                i_pco2_product)
  }
  
  if (!exists("pco2_product")) {
    pco2_product <- i_pco2_product
  }
  
}

rm(CMEMS_files, i_pco2_product, i_name, names)
# rm(pco2_product)

pco2_product <- pco2_product %>%
  as_tibble()


pco2_product <-
  pco2_product %>%
  rename(lon = x,
         lat = y,
         sfco2 = fuCO2_mean,
         fgco2 = fCO2_mean) %>% 
  select(-contains("_std")) %>% 
  units::drop_units()

pco2_product <-
  pco2_product %>%
  mutate(area = earth_surf(lat, lon),
         year = year(time),
         month = month(time))

pco2_product <-
  pco2_product %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon),
         fgco2 = -fgco2)

pco2_product <-
  pco2_product %>% 
  filter(year <= 2023)

```


```{r source_pCO2_product_preprocessing_child}

pCO2_product_preprocessing <-
  knitr::knit_expand(file = here::here("analysis/child/pCO2_product_preprocessing.Rmd"))

```


`r knitr::knit(text = unlist(pCO2_product_preprocessing))`

```{r source_pCO2_product_analysis_child_2023}

pCO2productanalysis_2023 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "CMEMS",
    year_anom = 2023
  )


```

`r knitr::knit(text = unlist(pCO2productanalysis_2023))`

```{r source_pCO2_product_analysis_child_2016}

pCO2productanalysis_2016 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "CMEMS",
    year_anom = 2016
  )


```

`r knitr::knit(text = unlist(pCO2productanalysis_2016))`

```{r source_pCO2_product_analysis_child_1998}

pCO2productanalysis_1998 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "CMEMS",
    year_anom = 1998
  )


```

`r knitr::knit(text = unlist(pCO2productanalysis_1998))`
