---
title: "CMEMS"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_read_data, include = FALSE}

library(stars)
library(lubridate)

```

# Read data

```{r define_paths}

path_pCO2_products <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/"

path_CMEMS <- paste0(path_pCO2_products, "cmems_ffnn/v2022/r100/")

```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)
nc <-
  nc_open(paste0(
    path_pCO2_products,
    "VLIZ-SOM_FFN/VLIZ-SOM_FFN_vBAMS2024.nc"
  ))

nc <-
  nc_open(paste0(
    path_CMEMS,
    "kw_OceanSODA_ETHZ_HR_LR-v2023.01-1982_2023.nc"
  ))

nc <-
  nc_open(paste0(
    path_CMEMS,
    "CO2_fluxes/fluxCO2_model_v2022_r100_202402.nc"
  ))

print(nc)

```


```{r read_CMEMS}

names <- c("CO2_fluxes", "CO2_fugacity")

for (i_name in names) {
  
  # i_name <- names[2]
  
  CMEMS_files <- list.files(path = paste0(path_CMEMS, i_name, "/"),
                            full.names = TRUE)
  
  # i_CMEMS_files <- CMEMS_files[2]
  
  i_pco2_product <-
    read_stars(CMEMS_files,
               make_units = FALSE,
               ignore_bounds = TRUE,
               quiet = TRUE)
  
  if (exists("pco2_product")) {
    pco2_product <-
      c(pco2_product,
                i_pco2_product)
  }
  
  if (!exists("pco2_product")) {
    pco2_product <- i_pco2_product
  }
  
}

rm(CMEMS_files, i_pco2_product, i_name, names)
# rm(pco2_product)

pco2_product <- pco2_product %>%
  as_tibble()


pco2_product <-
  pco2_product %>%
  rename(lon = x,
         lat = y,
         sfco2 = fuCO2_mean,
         fgco2 = fCO2_mean) %>% 
  select(-contains("_std")) %>% 
  units::drop_units()

pco2_product <-
  pco2_product %>%
  mutate(area = earth_surf(lat, lon),
         year = year(time),
         month = month(time))

pco2_product <-
  pco2_product %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon),
         fgco2 = -fgco2)

pco2_product <-
  pco2_product %>% 
  filter(year <= 2023)

```


```{r source_pCO2_product_preprocessing_child}

pCO2_product_preprocessing <-
  knitr::knit_expand(file = here::here("analysis/child/pCO2_product_preprocessing.Rmd"))

```


`r knitr::knit(text = unlist(pCO2_product_preprocessing))`

```{r source_pCO2_product_analysis_child}

pCO2_product_analysis <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "CMEMS",
    year_anom = 2022
  )


```


`r knitr::knit(text = unlist(pCO2_product_analysis))`
