---
title: "CMEMS_GCB"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_read_data, include = FALSE}

library(lubridate)
library(tidync)

```

# Read data

```{r define_paths}

path_pCO2_products <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/gcb_2024_pco2_products/"

```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)
nc <-
  nc_open(paste0(
    path_pCO2_products,
    "GCB-2024_dataprod_CMEMS-LSCE-FFNN_1990-2023_r100_v6.nc"
  ))

time <- ncvar_get(nc,"time")
time

print(nc)
ncmeta::nc_extended(nc)

```


```{r read_CMEMS}

pco2_product_nc <-
  tidync(
    paste0(
      path_pCO2_products,
      "GCB-2024_dataprod_CMEMS-LSCE-FFNN_1990-2023_r100_v6.nc"
    )
  )

for (i in 1:468) {
  
  i_pco2_product <-
    pco2_product_nc %>%
    hyper_filter(time = index == i) %>%
    hyper_tibble(select_var = c("fco2atm", "fgco2", "kw", "alpha", "sfco2", "tos")) %>%
    mutate(time = ymd("1990-01-15") %m+% months(i-1))
  
  if (exists("pco2_product")) {
    pco2_product <-
      bind_rows(pco2_product, i_pco2_product)
  }
  
  if (!exists("pco2_product")) {
    pco2_product <- i_pco2_product
  }
  
  # print(i)
  
}

pco2_product_fgco2 <-
  pco2_product %>% 
  select(lon, lat, time, fgco2) %>% 
  mutate(time = time - years(5))

# pco2_product_fgco2 %>% 
#   distinct(time) %>% 
#   pull()
# 
# pco2_product %>% 
#   distinct(time) %>% 
#   pull()

pco2_product <-
  full_join(pco2_product %>% select(-fgco2) %>% filter(time < ymd("2024-01-01")),
            pco2_product_fgco2 %>% filter(time > ymd("1990-01-01")))

pco2_product <-
  pco2_product %>%
  rename(temperature = tos,
         atm_fco2 = fco2atm,
         sol = alpha)

pco2_product <-
  pco2_product %>%
  mutate(lon = as.numeric(lon),
         lat = as.numeric(lat),
         area = earth_surf(lat, lon),
         year = year(time),
         month = month(time))

pco2_product <-
  pco2_product %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))

pco2_product <-
  pco2_product %>%
  mutate(dfco2 = sfco2 - atm_fco2)

pco2_product <-
  pco2_product %>% 
  mutate(fgco2 = -fgco2 * 60 * 60 * 24 * 365,
         kw_sol = kw * sol * 1e-2 * 24 * 365 * 1.025e-3)

pco2_product <-
  pco2_product %>%
  select(-c(kw, sol))

```



```{r source_pCO2_product_preprocessing_child}

pCO2_product_preprocessing <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_preprocessing.Rmd"),
    product_name = "CMEMS_GCB"
  )

```


`r knitr::knit(text = unlist(pCO2_product_preprocessing))`


```{r source_pCO2_product_analysis_child_2023}

pCO2_product_analysis_2023 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "CMEMS_GCB",
    year_anom = 2023
  )


```

`r knitr::knit(text = unlist(pCO2_product_analysis_2023))`

