---
title: "ETHZ CESM"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_read_data, include = FALSE}

library(stars)
library(lubridate)
library(seacarb)
library(tidync)

```

# Read data

```{r define_paths}

path_pCO2_products <-
  "/net/kryo/work/loher/GlobalMarineHeatwaves/ETHZ_BEC/"

```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)

nc <-
  nc_open(paste0(
    path_pCO2_products,
    "Heatwaves_RunA.nc"
  ))

print(nc)

```

```{r read_ETHZ_CESM_3d}

# pco2_product <-
#   read_mdim(
#     paste0(
#       path_pCO2_products,
#       "Heatwaves_RunA.nc"
#     ),
#     var = c("dissic")
#   )

pco2_product_interior <-
  tidync(paste0(path_pCO2_products,
                        "Heatwaves_RunA.nc"))

pco2_product_interior <- pco2_product_interior %>%
  hyper_filter(depth = depth <= 500) %>% 
  hyper_tibble(select_var = c("thetao", "dissic", "no3", "o2", "talk"),
                       force = TRUE)

pco2_product_interior <-
  pco2_product_interior %>%
  filter(thetao < 1e36)

gc()

pco2_product_interior <-
  pco2_product_interior %>%
  mutate(time = ymd_hms("1980-01-01 00:00:00") + days(time))

# pco2_product_interior <-
#   pco2_product_interior %>%
#   rename(temperature = thetao)

pco2_product_interior <-
  pco2_product_interior %>%
  mutate(
    lon = if_else(lon < 20, lon + 360, lon),
    dissic = dissic * 1.025e3,
    talk = talk * 1.025e3,
    no3 = no3 * 1.025e3,
    o2 = o2 * 1.025e3
  )
gc()

# pco2_product_interior_sub <-
#   pco2_product_interior %>%
#   filter(time == max(time))
# 
# pco2_product_interior_sub %>%
#   filter(depth == 5) %>%
#   ggplot(aes(lon, lat, fill = thetao)) +
#   geom_raster() +
#   scale_fill_viridis_c(option = "magma") +
#   coord_quickmap(expand = 0)
# 
# pco2_product_interior_sub %>%
#   filter(lon == 330.5) %>%
#   ggplot(aes(lat, depth, z = thetao)) +
#   geom_contour_filled(breaks = seq(-10,40,2)) +
#   scale_y_reverse() +
#   coord_cartesian(expand = 0) +
#   scale_fill_viridis_d(option = "magma")


```

```{r read_ETHZ_CESM}

print("Heatwaves_RunA.nc")

pco2_product <-
  read_ncdf(
    paste0(
      path_pCO2_products,
      "Heatwaves_RunA.nc"
    ),
    var = c("chlos", "sos", "tos", "Kw", "sfco2", "fgco2", "mld", "pco2", "pco2atm", "patm", "alpha", "zos", "intpp", "no3os", "o2os", "dissicos"),
    make_units = FALSE
  )


pco2_product <-
  pco2_product %>%
  as_tibble()


pco2_product <-
  pco2_product %>%
  rename(chl = chlos,
         kw = Kw,
         salinity = sos,
         temperature = tos,
         sol = alpha,
         press = patm,
         SSH = zos,
         no3 = no3os,
         o2 = o2os,
         dissic = dissicos)


pco2_product <-
  pco2_product %>%
  mutate(year = year(time),
         month = month(time))

pco2_product <-
  pco2_product %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon),
         chl = if_else(chl > 0, log10(chl * 10^6), 0),
         kw = kw *60 *60 *24 *365,
         # mld = log10(mld),
         fgco2 = -fgco2 *60 *60 *24 *365,
         sol = sol * 1.025e3 * 1e-6,
         dissic = dissic * 1.025e3,
         no3 = no3 * 1.025e3,
         o2 = o2 * 1.025e3)

pco2_product <-
  pco2_product %>%
  mutate(
    sfco2 = p2fCO2(T = temperature,
                   pCO2 = pco2),
    atm_fco2 = p2fCO2(T = temperature,
                      pCO2 = pco2atm),
    dfco2 = sfco2 - atm_fco2
  )

pco2_product <-
  pco2_product %>%
  select(-c(pco2, pco2atm))

pco2_product <-
  pco2_product %>% 
  mutate(kw_sol = kw * sol)


```



```{r source_pCO2_product_preprocessing_child}

pCO2_product_preprocessing <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_preprocessing.Rmd"),
    product_name = "ETHZ_CESM"
  )

```


`r knitr::knit(text = unlist(pCO2_product_preprocessing))`

```{r source_pCO2_product_analysis_child_2023}

pCO2productanalysis_2023 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "ETHZ_CESM",
    year_anom = 2023
  )


```

`r knitr::knit(text = unlist(pCO2productanalysis_2023))`
