---
title: "FESOM-REcoM"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_read_data, include = FALSE}

library(stars)
library(lubridate)
library(seacarb)
library(collapse)

```


# Read data

```{r define_paths}

path_FESOM <-
  "/net/kryo/work/loher/GlobalMarineHeatwaves/AWI_FESOM2/"


```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)

nc <-
  nc_open(paste0(
    path_FESOM,
    "dissic_FESOM2_REcoM_A_1_gr_1980-2023_v20220716.nc"
  ))

print(nc)

```


```{r read_FESOM-REcoM_interior}

FESOM_files <- list.files(path = path_FESOM)

FESOM_files <-
  FESOM_files[FESOM_files %>% str_detect(c(
    "dissic_|no3|thetao|talk_"
  ))]


dates <- seq(ymd("1980-01-15"), ymd("2023-12-15"), "months")


for (i_FESOM_files in FESOM_files) {
  
  # i_FESOM_files <- FESOM_files[1]
  
  i_pco2_product_interior <-
    read_mdim(paste0(path_FESOM,
                     i_FESOM_files))
  
  i_pco2_product_interior <-
    i_pco2_product_interior %>%
    filter(Depth <= 500)
  
  i_pco2_product_interior <- 
    st_set_dimensions(i_pco2_product_interior, 4, values = dates, names = "time")

  if (exists("pco2_product_interior")) {
    pco2_product_interior <-
      c(pco2_product_interior,
                i_pco2_product_interior)
  }
  
  if (!exists("pco2_product_interior")) {
    pco2_product_interior <- i_pco2_product_interior
  }
  
}

rm(FESOM_files, i_FESOM_files, i_pco2_product_interior)
# rm(pco2_product_interior)

pco2_product_interior <- pco2_product_interior %>%
  as_tibble()

pco2_product_interior <- pco2_product_interior %>%
  drop_na()
gc()


pco2_product_interior <-
  pco2_product_interior %>%
  rename(lat = Lat,
         lon = Lon,
         depth = Depth)

pco2_product_interior <-
  pco2_product_interior %>%
  mutate(
    lon = if_else(lon < 20, lon + 360, lon),
    no3 = no3 * 1.025e3,
    dissic = dissic * 1.025e3,
    talk = talk * 1.025e3,
    cstar = dissic  - (117/16 * no3)  - 0.5 * (talk + no3)
  )
gc()


pco2_product_surf <-
  pco2_product_interior %>%
  filter(depth == min(depth))

gc()


```


```{r read_FESOM-REcoM}

FESOM_files <- list.files(path = path_FESOM)

FESOM_files <-
  FESOM_files[FESOM_files %>% str_detect(c(
    "alpha|chlos|fgco2|Kw|mld|fCO2atm|sfco2|sos|tos|intpp|dissicos|talkos"
  ))]

for (i_FESOM_files in FESOM_files) {
  
  # i_FESOM_files <- FESOM_files[1]
  
  i_pco2_product <-
    read_ncdf(paste0(path_FESOM,
                     i_FESOM_files))
  
  i_pco2_product <- 
    st_set_dimensions(i_pco2_product, 3, values = dates, names = "time")
  
  if (exists("pco2_product")) {
    pco2_product <-
      c(pco2_product,
                i_pco2_product)
  }
  
  if (!exists("pco2_product")) {
    pco2_product <- i_pco2_product
  }
  
}

rm(FESOM_files, i_FESOM_files, i_pco2_product)
# rm(pco2_product)

pco2_product <- pco2_product %>%
  as_tibble()


pco2_product <-
  pco2_product %>%
  rename(lat = Lat,
         lon = Lon) %>% 
  mutate(year = year(time),
         month = month(time))

pco2_product <-
  pco2_product %>%
  rename(sol = alpha,
         chl = chlos,
         kw = Kw,
         atm_fco2 = fCO2atm,
         salinity = sos,
         temperature = tos,
         dissic = dissicos,
         talk = talkos) %>%
  mutate(
    lon = if_else(lon < 20, lon + 360, lon),
    chl = log10(chl * 1e6),
    kw = kw * 60 * 60 * 24 * 365,
    # mld = log10(-mld),
    sol = sol * 1.025e3 * 1e-6,
    fgco2 = -fgco2 * 60 * 60 * 24 * 365,
    dfco2 = sfco2 - atm_fco2,
    dissic = dissic * 1.025e3,
    talk = talk * 1.025e3
  )

pco2_product <-
  pco2_product %>% 
  mutate(kw_sol = kw * sol)

pco2_product <- 
  full_join(pco2_product,
            pco2_product_surf %>% select(-c(depth, thetao, dissic, talk, cstar)))

rm(pco2_product_surf)
gc()

# pco2_product %>% 
#   filter(time == max(time)) %>% 
#   select(lon, lat, temperature, sol, dissic) %>% 
#   ggplot(aes(lon, lat, fill = sol)) +
#   geom_tile() +
#   scale_fill_viridis_c()

```


```{r source_pCO2_product_preprocessing_child}

pCO2_product_preprocessing <-
  knitr::knit_expand(file = here::here("analysis/child/pCO2_product_preprocessing.Rmd"),
                     product_name = "FESOM-REcoM")

```


`r knitr::knit(text = unlist(pCO2_product_preprocessing))`


```{r source_pCO2_product_analysis_child_2023}

pCO2productanalysis_2023 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "FESOM-REcoM",
    year_anom = 2023
  )


```

`r knitr::knit(text = unlist(pCO2productanalysis_2023))`
