---
title: "pCO2 products"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_specific, include = FALSE}

library(stars)
library(lubridate)
library(ggnewscale)
library(khroma)
library(broom)

```

# Read data

```{r define_paths}

path_pCO2_products <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/"

path_reccap2 <-
  "/nfs/kryo/work/datasets/gridded/ocean/interior/reccap2/"

```

```{r read_region_mask}

region_masks_all <-
  read_ncdf(
    paste(
      path_reccap2,
      "supplementary/RECCAP2_region_masks_all_v20221025.nc",
      sep = ""
    )
  ) %>%
  as_tibble()

```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)
nc <-
  nc_open(paste0(
    path_pCO2_products,
    "VLIZ-SOM_FFN/VLIZ-SOM_FFN_vBAMS2024.nc"
  ))

print(nc)

```


```{r read_VLIZ_SOM_FFN}

SOM_FFN <-
  read_ncdf(
    paste0(
      path_pCO2_products,
      "VLIZ-SOM_FFN/VLIZ-SOM_FFN_vBAMS2024.nc"
    ),
    var = c("dco2", "atm_co2", "sol", "kw", "spco2_smoothed", "fgco2_smoothed"),
    make_units = FALSE
  )

SOM_FFN <- SOM_FFN %>%
  as_tibble()

SOM_FFN <-
  SOM_FFN %>%
  mutate(across(dco2:fgco2_smoothed, ~ replace(., . >= 1e+19, NA)))

SOM_FFN <-
  SOM_FFN %>%
  mutate(area = earth_surf(lat, lon),
         year = year(time),
         month = month(time)) %>% 
  filter(year >= 1990)

SOM_FFN <-
  SOM_FFN %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))

```

# Analysis settings

```{r analysis_settings}

key_biomes <- c("global",
                "NA-SPSS",
                "NA-STPS",
                "NP-SPSS",
                "PEQU-E",
                "SO-SPSS")

name_quadratic_fit <- c("atm_co2", "spco2_smoothed")

```


# Biome mask

```{r prepare_region_mask, fig.asp=0.5}

region_masks_all <-
  region_masks_all %>%
  mutate(lon = if_else(lon < 20, lon + 360, lon))

land_mask <- region_masks_all %>%
  filter(seamask == 0)

map <- ggplot(land_mask,
              aes(lon, lat)) +
  geom_tile(fill = "grey80") +
  coord_quickmap(expand = 0) +
  theme(axis.title = element_blank())


region_masks_all <- region_masks_all %>%
  filter(seamask == 1) %>% 
  select(lon, lat, atlantic:southern) %>% 
  pivot_longer(atlantic:southern,
               names_to = "region",
               values_to = "biome") %>%
  mutate(biome = as.character(biome))

region_masks_all <- region_masks_all %>%
  filter(biome != "0")

region_masks_all <- region_masks_all %>%
  mutate(biome = paste(region, biome, sep = "_"))


# map +
#   geom_raster(data = region_masks_all,
#               aes(lon, lat, fill = biome))


region_masks_all <- region_masks_all  %>% 
  mutate(biome = case_when(
    biome == "atlantic_1" ~ "NA-SPSS",
    biome == "atlantic_2" ~ "NA-STSS",
    biome == "atlantic_3" ~ "NA-STPS",
    biome == "atlantic_4" ~ "AEQU",
    biome == "atlantic_5" ~ "SA-STPS",
    biome == "atlantic_6" ~ "MED",
    biome == "pacific_1" ~ "NP-SPSS",
    biome == "pacific_2" ~ "NP-STSS",
    biome == "pacific_3" ~ "NP-STPS",
    biome == "pacific_4" ~ "PEQU-W",
    biome == "pacific_5" ~ "PEQU-E",
    biome == "pacific_6" ~ "SP-STSS",
    biome == "indian_1" ~ "Arabian Sea",
    biome == "indian_2" ~ "Bay of Bengal",
    biome == "indian_3" ~ "Equatorial Indian",
    biome == "indian_4" ~ "Southern Indian",
    # biome == "arctic_1" ~ "ARCTIC-ICE",
    # biome == "arctic_2" ~ "NP-ICE",
    # biome == "arctic_3" ~ "NA-ICE",
    # biome == "arctic_4" ~ "Barents",
    str_detect(biome, "arctic") ~ "Arctic",
    biome == "southern_1" ~ "SO-STSS",
    biome == "southern_2" ~ "SO-SPSS",
    biome == "southern_3" ~ "SO-ICE",
    TRUE ~ "other"
  ))

region_masks_all <-
  region_masks_all %>%
  filter(biome != "other")


map +
  geom_tile(data = region_masks_all,
            aes(lon, lat, fill = region)) +
  scale_fill_muted()

region_masks_all %>%
  group_split(region) %>%
  # head(2) %>%
  map(~ map +
        geom_tile(data = .x,
                    aes(lon, lat, fill = biome)) +
        labs(title = .x$region) +
        scale_fill_okabeito())


map +
  geom_tile(data = region_masks_all %>% filter(biome %in% key_biomes),
            aes(lon, lat, fill = biome)) +
  labs(title = "Selected key biomes") +
  scale_fill_muted()

```


# pCO2 products

## Maps

### Climatologies

```{r climatology_maps, fig.asp=0.5}

SOM_FFN_annual_mean_maps <-
  SOM_FFN %>%
  group_by(year, lon, lat) %>%
  summarise(across(dco2:fgco2_smoothed,
                   ~ mean(.))) %>%
  ungroup()

SOM_FFN_climatology <-
  SOM_FFN_annual_mean_maps %>%
  filter(year <= 2022) %>%
  group_by(lon, lat) %>%
  summarise(across(dco2:fgco2_smoothed,
                   ~ mean(.))) %>%
  ungroup()

SOM_FFN_2023_anomaly <-
  bind_rows(
    SOM_FFN_climatology %>% mutate(reference = "climatology"),
    SOM_FFN_annual_mean_maps %>%
      filter(year == 2023) %>%
      select(-year) %>% 
      mutate(reference = "2023")
  )

SOM_FFN_2023_anomaly <-
  SOM_FFN_2023_anomaly %>%
  pivot_longer(-c(lon, lat, reference)) %>%
  pivot_wider(names_from = reference,
              values_from = value) %>%
  mutate(anomaly = `2023` - climatology)

SOM_FFN_2023_anomaly %>%
  group_split(name) %>%
  # head(1) %>%
  map(~ map +
        geom_tile(data = .x,
                  aes(lon, lat, fill = climatology)) +
        labs(title = .x$name) +
        scale_fill_viridis_c())

```

### Anomaly from climatology

```{r anomaly_from_climatology_maps}


SOM_FFN_2023_anomaly %>%
  group_split(name) %>%
  # head(1) %>%
  map(~ map +
        geom_tile(data = .x,
                  aes(lon, lat, fill = anomaly)) +
        labs(title = .x$name) +
        scale_fill_divergent())


```

### Anomaly from prediction

```{r anomaly_from_prediction_maps}

SOM_FFN_annual_mean_maps_coarse <-
  m_grid_horizontal_coarse(SOM_FFN_annual_mean_maps) %>%
  group_by(year, lon_grid, lat_grid) %>%
  summarise(across(dco2:fgco2_smoothed,
                   ~ mean(.))) %>%
  ungroup() %>% 
  rename(lon = lon_grid, lat = lat_grid) %>% 
  drop_na()

SOM_FFN_annual_mean_maps_coarse <-
  SOM_FFN_annual_mean_maps_coarse %>% 
  pivot_longer(-c(year:lat))


# Linear regression models

SOM_FFN_annual_mean_maps_coarse_lm <-
  SOM_FFN_annual_mean_maps_coarse %>%
  filter(year <= 2022,
         !(name %in% name_quadratic_fit)) %>% 
  nest(data = -c(name, lon, lat)) %>%
  mutate(fit = map(data, ~ lm(value ~ year, data = .x)),
         tidied = map(fit, tidy),
         augmented = map(fit, augment),
         glanced = map(fit, glance))


SOM_FFN_annual_mean_maps_coarse_lm_2023 <-
  full_join(
    SOM_FFN_annual_mean_maps_coarse_lm %>%
      unnest(tidied) %>%
      select(name, lon, lat, term, estimate) %>%
      pivot_wider(names_from = term,
                  values_from = estimate) %>%
      mutate(fit = `(Intercept)` + year * 2023) %>%
      select(name, lon, lat, fit) %>%
      mutate(year = 2023),
    SOM_FFN_annual_mean_maps_coarse %>%
      filter(year == 2023,
             !(name %in% name_quadratic_fit))
  ) %>% 
  mutate(resid = value - fit)


SOM_FFN_annual_mean_maps_coarse_lm <-
  bind_rows(
    SOM_FFN_annual_mean_maps_coarse_lm %>%
      unnest(augmented) %>%
      select(name, lon, lat, year, value, fit = .fitted, resid = .resid),
    SOM_FFN_annual_mean_maps_coarse_lm_2023
  )

rm(SOM_FFN_annual_mean_maps_coarse_lm_2023)

# Quadratic regression models

SOM_FFN_annual_mean_maps_coarse_quadratic <-
  SOM_FFN_annual_mean_maps_coarse %>%
  filter(year <= 2022,
         name %in% name_quadratic_fit) %>% 
  nest(data = -c(name, lon, lat)) %>%
  mutate(fit = map(data, ~ lm(value ~ year + I(year^2), data = .x)),
         tidied = map(fit, tidy),
         augmented = map(fit, augment),
         glanced = map(fit, glance))


SOM_FFN_annual_mean_maps_coarse_quadratic_2023 <-
  full_join(
    SOM_FFN_annual_mean_maps_coarse_quadratic %>%
      unnest(tidied) %>%
      select(name, lon, lat, term, estimate) %>%
      pivot_wider(names_from = term,
                  values_from = estimate) %>%
      mutate(fit = `(Intercept)` + year * 2023 + `I(year^2)` * 2023 ^ 2) %>%
      select(name, lon, lat, fit) %>%
      mutate(year = 2023),
    SOM_FFN_annual_mean_maps_coarse %>%
      filter(year == 2023,
             name %in% name_quadratic_fit)
  ) %>% 
  mutate(resid = value - fit)


SOM_FFN_annual_mean_maps_coarse_quadratic <-
  bind_rows(
    SOM_FFN_annual_mean_maps_coarse_quadratic %>%
      unnest(augmented) %>%
      select(name, lon, lat, year, value, fit = .fitted, resid = .resid),
    SOM_FFN_annual_mean_maps_coarse_quadratic_2023
  )

rm(SOM_FFN_annual_mean_maps_coarse_quadratic_2023)

# Join linear and quadratic regression results

SOM_FFN_annual_mean_maps_coarse_regression <-
  bind_rows(SOM_FFN_annual_mean_maps_coarse_lm,
            SOM_FFN_annual_mean_maps_coarse_quadratic)

rm(SOM_FFN_annual_mean_maps_coarse_lm,
   SOM_FFN_annual_mean_maps_coarse_quadratic)

SOM_FFN_annual_mean_maps_coarse_regression %>%
  filter(year %in% c(min(year), max(year))) %>%
  select(-c(value, resid)) %>% 
  pivot_wider(names_from = year,
              values_from = fit) %>% 
  mutate(change = `2023` - `1990`) %>% 
  group_split(name) %>% 
  # head(1) %>%
  map( ~ map +
         geom_tile(data = .x,
                   aes(lon, lat, fill = change)) +
         facet_wrap( ~ name) +
         scale_fill_divergent(name = "change\n1990-2023"))

SOM_FFN_annual_mean_maps_coarse_regression %>%
  filter(year == 2023) %>%
  group_split(name) %>% 
  # head(1) %>% 
  map( ~ map +
         geom_tile(data = .x,
                   aes(lon, lat, fill = resid)) +
         facet_wrap( ~ name) +
         scale_fill_divergent(name = "2023\nanomaly"))


```


## Regional means and integrals



```{r global_means_and_integrals}

SOM_FFN <-
  inner_join(SOM_FFN,
             region_masks_all)

SOM_FFN_monthly_global <-
  SOM_FFN %>%
  group_by(time) %>% 
  summarise(across(dco2:spco2_smoothed, 
                   ~weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_smoothed, 
                   ~sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>% 
  ungroup()

SOM_FFN_monthly_biome <-
  SOM_FFN %>%
  group_by(time, region, biome) %>% 
  summarise(across(dco2:spco2_smoothed, 
                   ~weighted.mean(., area, na.rm = TRUE)),
            across(fgco2_smoothed, 
                   ~sum(. * area, na.rm = TRUE) * 12.01 * 1e-15)) %>% 
  ungroup()
  
SOM_FFN_monthly <- 
  bind_rows(SOM_FFN_monthly_global %>% 
              mutate(biome = "global",
                     region = "global"),
            SOM_FFN_monthly_biome)

rm(SOM_FFN_monthly_global,
   SOM_FFN_monthly_biome)


SOM_FFN_monthly <-
SOM_FFN_monthly %>%
  mutate(year = year(time),
         month = month(time),
         .after = time)

SOM_FFN_monthly <-
  SOM_FFN_monthly %>%
  pivot_longer(-c(time:month, biome, region))




```


### Seasonality

```{r seasonality_overview}

SOM_FFN_monthly %>%
  filter(biome %in% key_biomes) %>%
  ggplot(aes(month, value, group = as.factor(year))) +
  geom_path(data = . %>% filter(year < 2022),
            aes(col = year)) +
  scale_color_grayC() +
  new_scale_color() +
  geom_path(data = . %>% filter(year >= 2022),
            aes(col = as.factor(year)),
            linewidth = 1) +
  scale_color_manual(values = c("orange", "red"),
                     guide = guide_legend(reverse = TRUE,
                                          order = 1)) +
  scale_x_continuous(breaks = seq(1, 12, 3), expand = c(0, 0)) +
  facet_grid(name ~ biome, scales = "free_y") +
  theme(legend.title = element_blank(),
        axis.title.y = element_blank())


```


```{r seasonality_key_biomes, fig.asp=1.5}

SOM_FFN_monthly %>%
  filter(biome %in% key_biomes) %>%
  group_split(biome) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(month, value, group = as.factor(year))) +
      geom_path(data = . %>% filter(year < 2022),
                aes(col = year)) +
      scale_color_grayC() +
      new_scale_color() +
      geom_path(
        data = . %>% filter(year >= 2022),
        aes(col = as.factor(year)),
        linewidth = 1
      ) +
      scale_color_manual(
        values = c("orange", "red"),
        guide = guide_legend(reverse = TRUE,
                             order = 1)
      ) +
      scale_x_continuous(breaks = seq(1, 12, 3), expand = c(0, 0)) +
      facet_grid(name ~ biome, scales = "free_y") +
      theme(legend.title = element_blank(),
            axis.title.y = element_blank())
  )

```

## Trends annual means

```{r annual_mean_trends}

SOM_FFN_annual <-
  SOM_FFN_monthly %>%
  group_by(year, region, biome, name) %>%
  summarise(value = mean(value)) %>%
  ungroup()
  
SOM_FFN_annual %>% 
  filter(biome %in% key_biomes) %>%
  ggplot(aes(year, value)) +
  geom_point() +
  geom_smooth(data = . %>% filter(year <= 2022,
                                  !(name %in% name_quadratic_fit)),
              method = "lm",
              fullrange = TRUE,
              aes(col = "linear"),
              se = FALSE) +
  geom_smooth(data = . %>% filter(year <= 2022,
                                  name %in% name_quadratic_fit),
              method = "lm",
              fullrange = TRUE,
              formula = y ~ x + I(x^2),
              aes(col = "quadratic"),
              se = FALSE) +
  scale_color_brewer(
    palette = "Set1",
    name = "Regression fit\n prior 2023") +
  scale_x_continuous(breaks = seq(1980, 2020, 20)) +
  facet_grid(name ~ biome, scales = "free_y") +
  theme(axis.title.y = element_blank())

# Linear regression models

SOM_FFN_annual_lm <-
  SOM_FFN_annual %>%
  filter(year <= 2022,
         !(name %in% name_quadratic_fit)) %>% 
  nest(data = -c(biome, name)) %>%
  mutate(fit = map(data, ~ lm(value ~ year, data = .x)),
         tidied = map(fit, tidy),
         augmented = map(fit, augment),
         glanced = map(fit, glance))


SOM_FFN_annual_lm_2023 <-
  full_join(
    SOM_FFN_annual_lm %>%
      unnest(tidied) %>%
      select(biome, name, term, estimate) %>%
      pivot_wider(names_from = term,
                  values_from = estimate) %>%
      mutate(fit = `(Intercept)` + year * 2023) %>%
      select(biome, name, fit) %>%
      mutate(year = 2023),
    SOM_FFN_annual %>%
      filter(year == 2023,
             !(name %in% name_quadratic_fit))
  ) %>% 
  mutate(resid = value - fit)


SOM_FFN_annual_lm <-
  bind_rows(
    SOM_FFN_annual_lm %>%
      unnest(augmented) %>%
      select(biome, name, year, value, fit = .fitted, resid = .resid),
    SOM_FFN_annual_lm_2023 %>% 
      select(-region)
  )

rm(SOM_FFN_annual_lm_2023)

# Quadratic regression models

SOM_FFN_annual_quadratic <-
  SOM_FFN_annual %>%
  filter(year <= 2022,
         name %in% name_quadratic_fit) %>% 
  nest(data = -c(biome, name)) %>%
  mutate(fit = map(data, ~ lm(value ~ year + I(year^2), data = .x)),
         tidied = map(fit, tidy),
         augmented = map(fit, augment),
         glanced = map(fit, glance))


SOM_FFN_annual_quadratic_2023 <-
  full_join(
    SOM_FFN_annual_quadratic %>%
      unnest(tidied) %>%
      select(biome, name, term, estimate) %>%
      pivot_wider(names_from = term,
                  values_from = estimate) %>%
      mutate(fit = `(Intercept)` + year * 2023 + `I(year^2)` * 2023 ^ 2) %>%
      select(biome, name, fit) %>%
      mutate(year = 2023),
    SOM_FFN_annual %>%
      filter(year == 2023,
             name %in% name_quadratic_fit)
  ) %>% 
  mutate(resid = value - fit)


SOM_FFN_annual_quadratic <-
  bind_rows(
    SOM_FFN_annual_quadratic %>%
      unnest(augmented) %>%
      select(biome, name, year, value, fit = .fitted, resid = .resid),
    SOM_FFN_annual_quadratic_2023 %>% 
      select(-region)
  )

rm(SOM_FFN_annual_quadratic_2023)

# Join linear and quadratic regression results

SOM_FFN_annual_regression <-
  bind_rows(SOM_FFN_annual_lm,
            SOM_FFN_annual_quadratic)

rm(SOM_FFN_annual_lm,
   SOM_FFN_annual_quadratic)



# SOM_FFN_annual_lm <-
#   SOM_FFN_annual_lm %>% 
#   mutate(resid = -resid)

SOM_FFN_annual_regression %>%
  filter(biome %in% key_biomes) %>%
  ggplot(aes(year, resid)) +
  geom_hline(yintercept = 0) +
  geom_path() +
  geom_point(data = . %>% filter(year < 2022),
             aes(fill = year),
             shape = 21) +
  scale_fill_grayC() +
  new_scale_fill() +
  geom_point(data = . %>% filter(year >= 2022),
             aes(fill = as.factor(year)),
             shape = 21, size = 2)  +
  scale_fill_manual(values = c("orange", "red"),
                     guide = guide_legend(reverse = TRUE,
                                          order = 1)) +
  scale_x_continuous(breaks = seq(1980, 2020, 20)) +
  labs(title = "Residual from trend in annual means (actual - predicted)") +
  facet_grid(name ~ biome, scales = "free_y") +
  theme(legend.title = element_blank(),
        axis.title = element_blank())

SOM_FFN_annual_regression %>%
  filter(biome != "global") %>%
  ggplot(aes(biome, resid)) +
  geom_hline(yintercept = 0) +
  geom_jitter(data = . %>% filter(year < 2022),
             aes(fill = year),
             shape = 21, width = 0.2) +
  scale_fill_grayC() +
  new_scale_fill() +
  geom_point(data = . %>% filter(year >= 2022),
             aes(fill = as.factor(year)),
             shape = 21, size = 2)  +
  scale_fill_manual(values = c("orange", "red"),
                     guide = guide_legend(reverse = TRUE,
                                          order = 1)) +
  labs(title = "Residual from trend in annual means (actual - predicted)") +
  facet_grid(name ~ ., scales = "free_y") +
  theme(legend.title = element_blank(),
        axis.title = element_blank())


```


## Detrended seasonality

### Predited annual mean removed

```{r detrended_seasonality}

SOM_FFN_monthly_detrended <-
full_join(SOM_FFN_monthly,
          SOM_FFN_annual_regression %>% select(-c(value, resid))) %>%
  mutate(value = value - fit)

SOM_FFN_monthly_detrended %>% 
  filter(biome %in% key_biomes) %>%
  ggplot(aes(month, value, group = as.factor(year))) +
  geom_path(data = . %>% filter(year < 2022),
            aes(col = year)) +
  scale_color_grayC() +
  new_scale_color() +
  geom_path(data = . %>% filter(year >= 2022),
            aes(col = as.factor(year)),
            linewidth = 1) +
  scale_color_manual(values = c("orange", "red"),
                     guide = guide_legend(reverse = TRUE,
                                          order = 1)) +
  scale_x_continuous(breaks = seq(1, 12, 3), expand = c(0, 0)) +
  labs(title = "Monthly anomalies from predicted annual mean") +
  facet_grid(name ~ biome, scales = "free_y") +
  theme(legend.title = element_blank(),
        axis.title.y = element_blank())

```


```{r seasonality_detrended_key_biomes, fig.asp=1.5}

SOM_FFN_monthly_detrended %>%
  filter(biome %in% key_biomes) %>%
  group_split(biome) %>%
  head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(month, value, group = as.factor(year))) +
      geom_path(data = . %>% filter(year < 2022),
                aes(col = year)) +
      scale_color_grayC() +
      new_scale_color() +
      geom_path(
        data = . %>% filter(year >= 2022),
        aes(col = as.factor(year)),
        linewidth = 1
      ) +
      scale_color_manual(
        values = c("orange", "red"),
        guide = guide_legend(reverse = TRUE,
                             order = 1)
      ) +
      scale_x_continuous(breaks = seq(1, 12, 3), expand = c(0, 0)) +
      facet_grid(name ~ biome, scales = "free_y") +
      theme(legend.title = element_blank(),
            axis.title.y = element_blank())
  )


```


