---
title: "pCO2 prediction skill"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r library}

library(lubridate)
library(scales)
library(RColorBrewer)
library(ggtext)
library(ggnewscale)

```


```{r read_anomaly_2023_monthly_mean_maps}

files <- list.files(here::here("data/"),
                    pattern = paste0(2023,"_map_monthly_anomaly.csv"),
                    full.names = TRUE)

pco2_product_coarse_monthly_regression <-
  read_csv(files,
           id = "product")

pco2_product_coarse_monthly_regression <-
  pco2_product_coarse_monthly_regression %>% 
  mutate(product = str_extract(product, "OceanSODAv2|SOM-FFN|CMEMS|fCO2-Residual|ETHZ-CESM|FESOM-REcoM"))

all_product_list <- c("OceanSODAv2",
                      "SOM-FFN",
                      "fCO2-Residual",
                      "CMEMS",
                      "ETHZ-CESM",
                      "FESOM-REcoM")

pco2_product_coarse_monthly_regression <-
  pco2_product_coarse_monthly_regression %>%
  mutate(
    product = factor(product, levels = all_product_list)
  ) %>%
  filter(!is.na(name))

pco2_product_list <- c("OceanSODAv2", "SOM-FFN", "fCO2-Residual", "CMEMS")

```


```{r read_map}

map <-
  read_rds(here::here("data/map.rds"))

key_biomes <-
  read_rds(here::here("data/key_biomes.rds"))


biome_mask <-
  read_rds(here::here("data/biome_mask.rds"))

map +
  geom_tile(data = biome_mask,
            aes(fill = biome))

biome_mask <-
  bind_rows(biome_mask,
            biome_mask %>%
              filter(!str_detect(biome, "SO-SPSS|SO-ICE|Arctic")) %>%
              mutate(biome = "Global non-polar"))


```



```{r read_SOCAT}

SOCAT_gridded_monthly <-
  read_csv(
    here::here(
      "data/SOCATv2024_prelim/SOCATv2024_tracks_gridded_monthly.csv"
    ),
    skip = 241
  )

SOCAT_gridded_monthly <-
  SOCAT_gridded_monthly %>%
  mutate(year = year(DATE),
         month = month(DATE)) %>%
  select(year,
         month,
         lat = LAT,
         lon = LON,
         sfco2_obs = FCO2_AVE_WEIGHTED_YEAR) %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))


SOCAT_gridded_monthly <-
  inner_join(
    SOCAT_gridded_monthly,
    biome_mask %>%
      filter(!str_detect(biome, "SO-SPSS|SO-ICE|Arctic|Global")) %>%
      select(lon, lat))

map +
  geom_tile(data = SOCAT_gridded_monthly %>% filter(year == 2023),
            aes(lon, lat, fill = sfco2_obs)) +
  scale_fill_viridis_c() +
  facet_wrap(~ month)

map +
  geom_tile(data = SOCAT_gridded_monthly %>% count(lat, lon),
            aes(lon, lat, fill = n)) +
  scale_fill_scico(palette = "grayC", trans = "log10")


SOCAT_gridded_monthly_raster <- rast(SOCAT_gridded_monthly %>%
                                       count(lon, lat), crs = "+proj=longlat")


SOCAT_gridded_monthly_raster <- project(SOCAT_gridded_monthly_raster, target_crs, method = "near")

SOCAT_gridded_monthly_tibble <- SOCAT_gridded_monthly_raster %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  drop_na()

SOCAT_gridded_monthly_raster_2023 <- rast(SOCAT_gridded_monthly %>%
                                       filter(year == 2023) %>% 
                                       count(lon, lat), crs = "+proj=longlat")


SOCAT_gridded_monthly_raster_2023 <- project(SOCAT_gridded_monthly_raster_2023, target_crs, method = "near")

SOCAT_gridded_monthly_tibble_2023 <- SOCAT_gridded_monthly_raster_2023 %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  drop_na()



bbox <- st_bbox(c(xmin = -180, xmax = 180, ymax = 76, ymin = -54), crs = st_crs(4326))
bbox <- st_as_sfc(bbox)
bbox_trans <- st_break_antimeridian(bbox, lon_0 = center)

bbox_graticules <- st_graticule(
  x = bbox_trans,
  crs = st_crs(bbox_trans),
  datum = st_crs(bbox_trans),
  lon = c(20, 20.001),
  lat = c(-54,76),
  ndiscr = 1e3,
  margin = 0.001
)

bbox_graticules_trans <- st_transform(bbox_graticules, crs = target_crs)
rm(bbox, bbox_trans)

# ggplot() +
#   geom_sf(data = worldmap_trans, fill = "grey", col="grey") +
#   geom_sf(data = coastline_trans) +
#   geom_sf(data = bbox_graticules_trans)

lat_lim <- ext(bbox_graticules_trans)[c(3,4)]*1.002
lon_lim <- ext(bbox_graticules_trans)[c(1,2)]*1.005

stations <-
  tibble(
    lon = c(-64, -170, -12),
    lat = c(32, 0, 30)
    # label = c(1, 2, 3)
  )

stations <-
  stations %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))

stations <-
  stations %>% as.matrix()

# pts = matrix(1:10, , 2)
# st_multipoint(pts)

stations <- st_multipoint(stations)

stations <- st_sfc(stations, crs = "+proj=longlat")
stations_trans <- st_transform(stations, crs = target_crs)

stations_tibble <- do.call(rbind, st_geometry(stations_trans)) %>% 
    as_tibble() %>% setNames(c("lon","lat"))

stations_tibble <- 
  bind_cols(stations_tibble, label = c(1,2,3))

# Bats: 31.5 - 32.5°N / 63.5 – 64.5°W
# Mid Pacific: 0.5°S-0.5°N/170.5°W
# VOS-Line: 29°N/13°W , 30°N/12°W , 31°N/11°W


ggplot() +
  geom_tile(data = SOCAT_gridded_monthly_tibble, aes(x = lon, y = lat, fill = n)) +
  scale_fill_scico(palette = "grayC",
                   begin = 0.2,
                   trans = "log10",
                   "Months with\nobservations\n1990-2022") +
  new_scale_fill() +
  geom_tile(data = SOCAT_gridded_monthly_tibble_2023, aes(x = lon, y = lat, fill = n)) +
  scale_fill_scico(palette = "buda",
                   trans = "log10",
                   "Months with\nobservations\n2023") +
  geom_sf(data = worldmap_trans,
          fill = "grey90",
          col = "grey90") +
  geom_sf(data = coastline_trans, linewidth = 0.3) +
  geom_sf(data = bbox_graticules_trans, linewidth = 0.5) +
  geom_label(data = stations_tibble, aes(x = lon, y = lat, label = label)) +
  coord_sf(
    crs = target_crs,
    ylim = lat_lim,
    xlim = lon_lim,
    expand = FALSE
  ) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_rect(colour = "transparent"),
    strip.background = element_blank(),
    legend.position = "top"
  )

ggsave(width = 8,
       height = 4.5,
       dpi = 600,
       filename = "../output/SOCAT_observations_map.jpg")



biome_mask_robin_raster <- rast(
  biome_mask %>%
    filter(!str_detect(biome, "SO-SPSS|SO-ICE|Arctic|Global")) %>%
    mutate(dist = 1) %>%
    mutate(biome = case_when(
      str_detect(biome, "SPSS") ~ "SPSS",
      str_detect(biome, "STSS") ~ "STSS",
      str_detect(biome, "STPS") ~ "STPS",
      TRUE ~ "Tropics"
    )) %>% 
    pivot_wider(names_from = biome, values_from = dist),
  crs = "+proj=longlat"
)


biome_mask_robin_raster <- project(biome_mask_robin_raster, target_crs, method = "near")

biome_mask_robin_tibble <- biome_mask_robin_raster %>%
  as.data.frame(xy = TRUE, na.rm = FALSE) %>%
  as_tibble() %>%
  rename(lon = x, lat = y) %>%
  pivot_longer(cols = -c("lon", "lat"),
               names_to = "biome",
               values_to = "dist") %>%
  drop_na() %>% 
  mutate(biome = as.character(biome))


ggplot() +
  geom_raster(
    data = biome_mask_robin_tibble %>% 
      mutate(biome = fct_inorder(biome)),
    aes(
      x = lon,
      y = lat,
      fill = biome
    )
  ) +
  geom_sf(data = worldmap_trans, fill = "grey90", col = "grey90") +
  geom_sf(data = coastline_trans, linewidth = 0.3) +
  geom_sf(data = bbox_graticules_trans, linewidth = 0.5) +
  coord_sf(
    crs = target_crs,
    ylim = lat_lim,
    xlim = lon_lim,
    expand = FALSE
  ) +
  scale_fill_viridis_d(option = "magma", begin = 0.1, end = 0.9)  +
  guides(fill = guide_legend(byrow = TRUE)) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_rect(colour = "transparent"),
    strip.background = element_blank(),
    legend.position = "top",
    legend.title = element_blank()
  )

ggsave(width = 8,
       height = 4.5,
       dpi = 600,
       filename = "../output/biome_map.jpg")

# SOCAT_gridded_monthly <-
#   m_grid_horizontal_coarse(SOCAT_gridded_monthly)
# 
# SOCAT_gridded_monthly <-
#   SOCAT_gridded_monthly %>%
#   mutate(area = earth_surf(lat, lon)) %>% 
#   group_by(year, month, lon_grid, lat_grid) %>%
#   summarise(across(sfco2_obs,
#                    ~ weighted.mean(., area, na.rm = TRUE))) %>%
#   ungroup() %>%
#   rename(lon = lon_grid, lat = lat_grid)
# 
# map +
#   geom_tile(data = SOCAT_gridded_monthly %>% filter(year == 2023),
#             aes(lon, lat, fill = sfco2_obs)) +
#   scale_fill_viridis_c() +
#   facet_wrap(~ month)

SOCAT_pCO2_product <-
  left_join(
    pco2_product_coarse_monthly_regression %>%
      filter(name == "sfco2"),
    SOCAT_gridded_monthly
  )


map +
  geom_tile(data = SOCAT_pCO2_product %>% filter(year == 2023),
            aes(lon, lat, fill = sfco2_obs)) +
  scale_fill_viridis_c() +
  facet_wrap(~ month)


```

```{r 2023_bias_maps}


SOCAT_pCO2_product <-
  SOCAT_pCO2_product %>%
  group_by(lon, lat, month, year) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n == 6) %>% 
  select(-n)

SOCAT_pCO2_product <-
  SOCAT_pCO2_product %>%
  mutate(sfco2_bias = value - sfco2_obs)

map +
  geom_tile(
    data = SOCAT_pCO2_product %>% filter(year == 2023,
                                         product %in% pco2_product_list) %>%
      group_by(lon, lat, month) %>%
      summarise(sfco2_bias = mean(sfco2_bias)) %>%
      ungroup(),
    aes(lon, lat, fill = sfco2_bias)
  ) +
  scale_fill_gradientn(
    colours = rev(brewer.pal(7, "Spectral")),
    rescaler = ~ scales::rescale_mid(.x, mid = 0),
    name = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)",
    # limits = c(
    #   quantile(SOCAT_pCO2_product$sfco2_bias, .01),
    #   quantile(SOCAT_pCO2_product$sfco2_bias, .99)
    # ),
    oob = squish
  ) +
  guides(
    fill = guide_colorbar(
      barheight = unit(0.3, "cm"),
      barwidth = unit(6, "cm"),
      ticks = TRUE,
      ticks.colour = "grey20",
      frame.colour = "grey20",
      label.position = "top",
      direction = "horizontal"
    )
  ) +
  theme(legend.title = element_markdown(),
        legend.position = "top") +
  facet_wrap(~ month)

ggsave(width = 7,
       height = 4,
       dpi = 600,
       filename = "../output/SOCAT_fco2_bias_map_2023_ensemble_mean.jpg")


map +
  geom_tile(data = SOCAT_pCO2_product %>% filter(year == 2023),
            aes(lon, lat, fill = sfco2_bias)) +
  scale_fill_gradientn(
    colours = rev(brewer.pal(7, "Spectral")),
    rescaler = ~ scales::rescale_mid(.x, mid = 0),
    name = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)",
    # limits = c(quantile(SOCAT_pCO2_product$sfco2_bias, .01), 
    #            quantile(SOCAT_pCO2_product$sfco2_bias, .99)),
    oob = squish
  ) +
  guides(
    fill = guide_colorbar(
      barheight = unit(0.3, "cm"),
      barwidth = unit(6, "cm"),
      ticks = TRUE,
      ticks.colour = "grey20",
      frame.colour = "grey20",
      label.position = "top",
      direction = "horizontal"
    )
  ) +
  theme(legend.title = element_markdown(),
        legend.position = "top") +
  facet_grid(month ~ product)

ggsave(width = 8,
       height = 7,
       dpi = 600,
       filename = "../output/SOCAT_fco2_bias_map_2023.jpg")


```


```{r biome_timeseries}

SOCAT_pCO2_product_biome <-
  inner_join(SOCAT_pCO2_product,
             biome_mask,
             relationship = "many-to-many")


SOCAT_pCO2_product_biome <-
  SOCAT_pCO2_product_biome %>%
  group_by(year, month, product, biome) %>%
  summarise(
    sfco2_bias = mean(sfco2_bias, na.rm = TRUE),
    sfco2_resid = mean(resid, na.rm = TRUE)
  ) %>%
  ungroup()
  
SOCAT_pCO2_product_biome %>%
  filter(biome %in% c("Global", key_biomes),
         year >= 2020,
         product %in% pco2_product_list) %>%
  group_by(biome, year, month) %>%
  summarise(sfco2_bias = mean(sfco2_bias, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(year + month / 12, sfco2_bias))+
  geom_hline(yintercept = 0) +
  geom_path() +
  geom_point(data = . %>% filter(year != 2023),
             aes(fill = "2020-2022"),
             size = 1) +
  scale_fill_manual(values = "grey70",name = "") +
  new_scale_fill() +
  geom_point(data = . %>% filter(year == 2023),
             aes(fill = month),
             shape = 21) +
  scale_fill_scico(
    palette = "buda",
    guide = guide_legend(reverse = TRUE,
                         order = 1),
    name = paste("Month\nof", 2023)
  ) +
  coord_cartesian(ylim = c(-50,50)) +
  scale_x_continuous(breaks = seq(1980, 2022, 2)) +
  labs(y = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)",) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_markdown()) +
  facet_wrap(~ biome)


ggsave(width = 7,
       height = 4,
       dpi = 600,
       filename = "../output/SOCAT_fco2_bias_timeseries_2018_2023_ensemble_mean.jpg")
  
SOCAT_pCO2_product_biome %>% 
  filter(biome %in% c("Global", key_biomes),
         year >= 2020) %>%
  ggplot(aes(year + month/12, sfco2_bias)) +
  geom_hline(yintercept = 0) +
  geom_path() +
  geom_point(data = . %>% filter(year != 2023),
             aes(fill = "2020-2022"),
             size = 1) +
  scale_fill_manual(values = "grey70",name = "") +
  new_scale_fill() +
  geom_point(data = . %>% filter(year == 2023),
             aes(fill = month),
             shape = 21) +
  scale_fill_scico(
    palette = "buda",
    guide = guide_legend(reverse = TRUE,
                         order = 1),
    name = paste("Month\nof", 2023)
  ) +
  coord_cartesian(ylim = c(-50,50)) +
  scale_x_continuous(breaks = seq(1980, 2022, 2)) +
  labs(y = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_markdown()) +
  facet_grid(biome ~ product)


ggsave(width = 10,
       height = 7,
       dpi = 600,
       filename = "../output/SOCAT_fco2_bias_timeseries_2018_2023.jpg")

```

```{r bias_anomaly_correlation}

SOCAT_pCO2_product_biome %>%
  mutate(month = as.factor(month)) %>%
  filter(biome %in% c("Global", key_biomes),
         product %in% pco2_product_list) %>%
  group_by(biome, year, month) %>%
  summarise(sfco2_bias = mean(sfco2_bias, na.rm = TRUE),
            sfco2_resid = mean(sfco2_resid, na.rm = TRUE)) %>%
  ungroup() %>%
  ggplot(aes(sfco2_bias, sfco2_resid)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point(data = . %>% filter(year != 2023),
             alpha = 0.1) +
  geom_path(data = . %>% filter(year == 2023)) +
  geom_point(
    data = . %>% filter(year == 2023),
    aes(fill = month),
    shape = 21,
    size = 2
  ) +
  scale_fill_scico_d(
    palette = "buda",
    guide = guide_legend(reverse = TRUE,
                         order = 1),
    name = paste("Month\nof", 2023)
  ) +
  coord_fixed(ylim = c(-50, 50),
              xlim = c(-50, 50)) +
  labs(x = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)",
       y = "fCO<sub>2,ocean</sub><br>anomaly<br>(µatm)") +
  facet_wrap(~ biome) +
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown()
  )


ggsave(width = 7,
       height = 4,
       dpi = 600,
       filename = "../output/SOCAT_fco2_anomaly_vs_bias_ensemble_mean.jpg")

SOCAT_pCO2_product_biome %>%
  mutate(month = as.factor(month)) %>%
  filter(biome %in% c("Global", key_biomes)) %>%
  ggplot(aes(sfco2_bias, sfco2_resid)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point(data = . %>% filter(year != 2023),
             alpha = 0.1) +
  geom_path(data = . %>% filter(year == 2023)) +
  geom_point(
    data = . %>% filter(year == 2023),
    aes(fill = month),
    shape = 21,
    size = 2
  ) +
  scale_fill_scico_d(
    palette = "buda",
    guide = guide_legend(reverse = TRUE,
                         order = 1),
    name = paste("Month\nof", 2023)
  ) +
  coord_fixed(ylim = c(-50, 50),
              xlim = c(-50, 50)) +
  labs(x = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)",
       y = "fCO<sub>2,ocean</sub><br>anomaly<br>(µatm)") +
  facet_grid(biome ~ product) +
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown()
  )


ggsave(width = 10,
       height = 7,
       dpi = 600,
       filename = "../output/SOCAT_fco2_anomaly_vs_bias.jpg")

SOCAT_pCO2_product_biome %>%
  mutate(month = as.factor(month)) %>%
  filter(biome %in% c("Global", key_biomes)) %>%
  ggplot(aes(sfco2_bias, sfco2_resid)) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point(data = . %>% filter(year != 2023),
             alpha = 0.1) +
  geom_path(data = . %>% filter(year == 2023)) +
  geom_point(
    data = . %>% filter(year == 2023),
    aes(fill = month),
    shape = 21,
    size = 2
  ) +
  scale_fill_scico_d(
    palette = "buda",
    guide = guide_legend(reverse = TRUE,
                         order = 1),
    name = paste("Month\nof", 2023)
  ) +
  coord_fixed(ylim = c(-20, 20),
              xlim = c(-20, 20)) +
  labs(x = "fCO<sub>2,ocean</sub> bias<br>pred. - obs.<br>(µatm)",
       y = "fCO<sub>2,ocean</sub><br>anomaly<br>(µatm)") +
  facet_grid(biome ~ product) +
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown()
  )


ggsave(width = 10,
       height = 7,
       dpi = 600,
       filename = "../output/SOCAT_fco2_anomaly_vs_bias_zoom.jpg")


```


```{r bias_all_biomes}

SOCAT_pCO2_product_biome %>%
  filter(biome %in% c("Global", key_biomes)) %>% 
  mutate(month = as.factor(month)) %>%
  ggplot(aes(sfco2_bias, product)) +
  geom_vline(xintercept = 0) +
  geom_jitter(data = . %>% filter(year != 2023),
             alpha = 0.1) +
  geom_jitter(
    data = . %>% filter(year == 2023),
    aes(fill = month),
    shape = 21,
    size = 2
  ) +
  scale_fill_scico_d(
    palette = "buda",
    guide = guide_legend(reverse = TRUE,
                         order = 1),
    name = paste("Month\nof", 2023)
  ) +
  scale_y_discrete(limits = rev) +
  coord_cartesian(xlim = c(-50, 50)) +
  labs(x = "fCO<sub>2,ocean</sub><br>bias<br>(µatm)") +
  facet_wrap( ~ biome) +
  theme(
    axis.title.x = element_markdown(),
    axis.title.y = element_markdown()
  )


ggsave(width = 10,
       height = 10,
       dpi = 600,
       filename = "../output/SOCAT_fco2_anomaly.jpg")



```

