---
title: "SOM_FFN_GCB"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r load_libraries_read_data, include = FALSE}

library(stars)
library(lubridate)
library(seacarb)

```

# Read data

```{r define_paths}

path_pCO2_products <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/VLIZ-SOM_FFN/"


path_NOAA_oisst <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/sst/noaa_oisst_20cm/"


path_OceanSODA <-
  "/nfs/kryo/work/datasets/gridded/ocean/2d/observation/pco2/gcb_2024_pco2_products/"



```


```{r read_nc_metadata, eval=FALSE}

library(ncdf4)
nc <-
  nc_open(paste0(
    path_pCO2_products,
    "VLIZ-SOM_FFN_v2025_predict.nc"
  ))

print(nc)

nc <-
  nc_open(paste0(
    path_NOAA_oisst,
    "SST-noaa_oisst2-P1D_m-2024.nc"
  ))

print(nc)

```


```{r read_VLIZ_SOM_FFN}

pco2_product <-
  read_ncdf(
    paste0(
      path_pCO2_products,
      "VLIZ-SOM_FFN_v2025_predict.nc"
    ),
    # var = c("fco2atm", "fgco2", "kw", "alpha", "sfco2", "tos"),
    var = c("spco2_smoothed", "fgco2_smoothed"),
    ignore_bounds = TRUE,
    make_units = FALSE
  )

pco2_product <- pco2_product %>%
  as_tibble()

pco2_product <- pco2_product %>%
  drop_na()

pco2_product <-
  pco2_product %>%
  rename(sfco2 = spco2_smoothed,
         fgco2 = fgco2_smoothed)

pco2_product <-
  pco2_product %>%
  filter(fgco2 < 10e19)

pco2_product <-
  pco2_product %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))


pco2_product <-
  pco2_product %>%
  mutate(area = earth_surf(lat, lon),
         year = year(time),
         month = month(time)) %>% 
  select(-time)

sst_2024 <-
  read_ncdf(
    paste0(
      path_NOAA_oisst,
      "SST-noaa_oisst2-P1D_m-2024.nc"
    ),
    var = "sst",
    ignore_bounds = TRUE,
    make_units = FALSE
  )

sst_2024 <- sst_2024 %>%
  as_tibble()

sst_2024 <- sst_2024 %>%
  drop_na()

sst_2024 <-
  sst_2024 %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))

# sst_2024 <- m_grid_horizontal(sst_2024)

sst_2024 <-
  sst_2024 %>%
  mutate(area = earth_surf(lat, lon),
         year = year(time),
         month = month(time)) %>% 
  select(-time)

# sst_2024 %>% 
#   group_by(year, month, lon, lat) %>% 
#   summarise(sst = weighted.mean(sst, area)) %>% 
#   ungroup()


sst <-
  read_ncdf(
    paste0(
      path_OceanSODA,
      "GCB-2024_dataprod_OceanSODA-ETHZv2_1982-2023.nc"
    ),
    var = c("tos"),
    ignore_bounds = TRUE,
    make_units = FALSE
  )

sst <- sst %>%
  as_tibble()

sst <- sst %>%
  drop_na()

sst <-
  sst %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon))

sst <-
  sst %>%
  mutate(area = earth_surf(lat, lon),
         year = year(time),
         month = month(time)) %>% 
  select(-time)

sst <- 
bind_rows(
  sst %>% rename(temperature = tos), 
  sst_2024 %>% rename(temperature = sst))

rm(sst_2024)

pco2_product <-
  inner_join(sst %>% select(-area), 
             pco2_product)

pco2_product <-
  pco2_product %>%
  mutate(time = ymd(paste(year, month, "15", sep = "-")))

rm(sst)
gc()

pco2_product <-
  pco2_product %>%
  mutate(atm_fco2 = 400,
         dfco2 = sfco2 - atm_fco2,
         kw_sol = 0.01)

# pco2_product <-
#   pco2_product %>%
#   mutate(dfco2 = sfco2 - atm_fco2)
# 
# pco2_product <-
#   pco2_product %>% 
#   mutate(fgco2 = -fgco2 * 60 * 60 * 24 * 365,
#          kw_sol = kw * sol * 1e-2 * 24 * 365)
# 
# pco2_product <-
#   pco2_product %>%
#   select(-c(kw, sol))

```



```{r source_pCO2_product_preprocessing_child}

pCO2_product_preprocessing <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_preprocessing.Rmd"),
    product_name = "SOM-FFN_predict"
  )

```


`r knitr::knit(text = unlist(pCO2_product_preprocessing))`


```{r source_pCO2_product_analysis_child_2024}

pCO2_product_analysis_2024 <-
  knitr::knit_expand(
    file = here::here("analysis/child/pCO2_product_analysis.Rmd"),
    product_name = "SOM-FFN_predict",
    year_anom = 2024
  )


```

`r knitr::knit(text = unlist(pCO2_product_analysis_2024))`

